server:
  port: 9192

spring:
  datasource:
    username: root
    password: wgcodeAdmin4
    url: jdbc:mysql://localhost:3306/student
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
